"""add overtime_minutes to attendance

Revision ID: 76ad5cda7f17
Revises: 
Create Date: 2025-12-25 11:33:55.179168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76ad5cda7f17'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paid_holidays',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True)
    )
    op.create_index(op.f('ix_paid_holidays_date'), 'paid_holidays', ['date'], unique=True)
    op.create_index(op.f('ix_paid_holidays_year'), 'paid_holidays', ['year'], unique=False)
    op.add_column(
        'attendance',
        sa.Column('overtime_minutes', sa.Integer(), nullable=True)
    )

    op.execute(
        "UPDATE attendance SET overtime_minutes = 0 WHERE overtime_minutes IS NULL"
    )

    op.alter_column(
        'attendance',
        'overtime_minutes',
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance', 'overtime_minutes')
    op.drop_index(op.f('ix_paid_holidays_year'), table_name='paid_holidays')
    op.drop_index(op.f('ix_paid_holidays_date'), table_name='paid_holidays')
    op.drop_table('paid_holidays')
    # ### end Alembic commands ###
